#kind: StorageClass
#apiVersion: storage.k8s.io/v1beta1
#metadata:
#     name: azure-disk
#provisioner: kubernetes.io/gce-pd
#parameters:
#  storageaccounttype: Standard_LRS
#  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-jrt
  #annotations:
    #volume.beta.kubernetes.io/storage-class: gce-pd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi