// <auto-generated />
using System;
using F19ITONK.ASPNETCore.MicroService.Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace F19ITONK.ASPNETCore.MicroService.Backend.Migrations
{
    [DbContext(typeof(BackendDBContext))]
    [Migration("20190227084413_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Haandvaerker", b =>
                {
                    b.Property<int>("HaandvaerkerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HVAnsaettelsedato");

                    b.Property<string>("HVEfternavn");

                    b.Property<string>("HVFagomraade");

                    b.Property<string>("HVFornavn");

                    b.HasKey("HaandvaerkerId");

                    b.ToTable("Haandvaerker");
                });

            modelBuilder.Entity("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Vaerktoej", b =>
                {
                    b.Property<long>("VTId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LiggerIvtk");

                    b.Property<int?>("LiggerIvtkNavigationVTKId");

                    b.Property<DateTime>("VTAnskaffet");

                    b.Property<string>("VTFabrikat");

                    b.Property<string>("VTModel");

                    b.Property<string>("VTSerienr");

                    b.Property<string>("VTType");

                    b.HasKey("VTId");

                    b.HasIndex("LiggerIvtkNavigationVTKId");

                    b.ToTable("Vaerktoej");
                });

            modelBuilder.Entity("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VTKId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EjesAfNavigationHaandvaerkerId");

                    b.Property<DateTime>("VTKAnskaffet");

                    b.Property<int?>("VTKEjesAf");

                    b.Property<string>("VTKFabrikat");

                    b.Property<string>("VTKFarve");

                    b.Property<string>("VTKModel");

                    b.Property<string>("VTKSerienummer");

                    b.HasKey("VTKId");

                    b.HasIndex("EjesAfNavigationHaandvaerkerId");

                    b.ToTable("Vaerktoejskasse");
                });

            modelBuilder.Entity("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Vaerktoej", b =>
                {
                    b.HasOne("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Vaerktoejskasse", "LiggerIvtkNavigation")
                        .WithMany("Vaerktoej")
                        .HasForeignKey("LiggerIvtkNavigationVTKId");
                });

            modelBuilder.Entity("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Vaerktoejskasse", b =>
                {
                    b.HasOne("F19ITONK.ASPNETCore.MicroService.ClassLib.Models.Haandvaerker", "EjesAfNavigation")
                        .WithMany("Vaerktoejskasse")
                        .HasForeignKey("EjesAfNavigationHaandvaerkerId");
                });
#pragma warning restore 612, 618
        }
    }
}
